# Univariate Analysis

In this dataset I will perform an **univariate analysis** of both numerical and categorical variables within the Ames Housing dataset.

This will allow me to understand the individual behavior of each feature before proceeding to multivariate analysis or predictive modeling.

## Imports and Data Loading

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
data_path = '../../data/raw/AmesHousing.csv'

df = pd.read_csv(data_path)
df.head(3)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   str
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   str
 7   Alley            198 non-null    str
 8   Lot Shape        2930 non-null   str
 9   Land Contour     2930 non-null   str
 10  Utilities        2930 non-null   str
 11  Lot Config       2930 non-null   str
 12  Land Slope       2930 non-null   str
 13  Neighborhood     2930 non-null   str
 14  Condition 1      2930 non-null   str
 15  Condition 2      2930 non-null   str
 16  Bldg Type        2930 non-null   str
 17  House Style      2930 non-null   str
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   str
 23  Roof Matl        2930 non-null   str
 24  Exterior 1st     2930 non-null   str
 25  Exterior 2nd     2930 non-null   str
 26  Mas Vnr Type     1155 non-null   str
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   str
 29  Exter Cond       2930 non-null   str
 30  Foundation       2930 non-null   str
 31  Bsmt Qual        2850 non-null   str
 32  Bsmt Cond        2850 non-null   str
 33  Bsmt Exposure    2847 non-null   str
 34  BsmtFin Type 1   2850 non-null   str
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   str
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   str
 41  Heating QC       2930 non-null   str
 42  Central Air      2930 non-null   str
 43  Electrical       2929 non-null   str
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   str
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   str
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   str
 59  Garage Type      2773 non-null   str
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   str
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   str
 65  Garage Cond      2771 non-null   str
 66  Paved Drive      2930 non-null   str
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     str
 74  Fence            572 non-null    str
 75  Misc Feature     106 non-null    str
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   str
 80  Sale Condition   2930 non-null   str
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), str(43)
memory usage: 1.8 MB

In [6]:
df['MS SubClass'] = df['MS SubClass'].astype('object') # this is a categorical variable although it is represented as a number

In [7]:
numerical_features = df.select_dtypes(include=[np.number]).columns.tolist()
print(numerical_features)

['Order', 'PID', 'Lot Frontage', 'Lot Area', 'Overall Qual', 'Overall Cond', 'Year Built', 'Year Remod/Add', 'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd', 'Fireplaces', 'Garage Yr Blt', 'Garage Cars', 'Garage Area', 'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold', 'SalePrice']

In [8]:
categorical_features = df.select_dtypes(include=['object', 'str']).columns.tolist()

print(categorical_features)

['MS SubClass', 'MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin Type 2', 'Heating', 'Heating QC', 'Central Air', 'Electrical', 'Kitchen Qual', 'Functional', 'Fireplace Qu', 'Garage Type', 'Garage Finish', 'Garage Qual', 'Garage Cond', 'Paved Drive', 'Pool QC', 'Fence', 'Misc Feature', 'Sale Type', 'Sale Condition']

## Descriptive Statistics for Numerical Variables

### Report for Numerical Features Descriptive Stats

In [9]:
def get_descriptive_stats_numerical_features(df, numerical_features):
    
    """This function returns a table with descriptive statistics for numerical features in the DataFrame. Such as:
    - Count
    - Mean
    - Median
    - Standard Deviation
    - Coefficient of Variation
    - Minimum and Maximum
    - Quartiles (Q1 and Q3)
    - Interquartile Range (IQR)
    - Skewness
    - Kurtosis
    """

    stats_list = []

    for feature in numerical_features:

        mean = df[feature].mean()
        median = df[feature].median()
        std = df[feature].std()
        
        coef_var = std / mean if mean != 0 else np.nan
        
        min, max = df[feature].min(), df[feature].max()
        range = max - min
        q1, q3 = df[feature].quantile(0.25), df[feature].quantile(0.75)
        iqr = q3 - q1
        skewness = df[feature].skew()
        kurtosis = df[feature].kurt()

        stats_list.append({
            "Feature" : feature,
            "Count" : df[feature].count(),
            "Mean" : f"{mean:.3f}",
            "Median" : f"{median:.3f}",
            "Std" : f"{std:.3f}",
            "Coefficient of Variation" : f"{coef_var:.4f}",
            "Min" : f"{min:.3f}",
            "Max" : f"{max:.3f}",
            "range" : f"{range:.3f}",
            "Q1" : f"{q1:.3f}",
            "Q3" : f"{q3:.3f}",
            "IQR" : f"{iqr:.3f}",
            "Skewness" : f"{skewness:.4f}",
            "Kurtosis" : f"{kurtosis:.4f}"
        })
    
    return stats_list

In [10]:
report = pd.DataFrame(get_descriptive_stats_numerical_features(df, numerical_features))
report

,Feature,Count,Mean,Median,Std,Coefficient of Variation,Min,Max,range,Q1,Q3,IQR,Skewness,Kurtosis
0,Order,2930,1465.500,1465.500,845.962,0.5773,1.000,2930.000,2929.000,733.250,2197.750,1464.500,0.0000,-1.2000
1,PID,2930,714464496.989,535453620.000,188730844.649,0.2642,526301100.000,1007100110.000,480799010.000,528477022.500,907181097.500,378704075.000,0.0559,-1.9951
2,Lot Frontage,2440,69.225,68.000,23.365,0.3375,21.000,313.000,292.000,58.000,80.000,22.000,1.4991,11.2349
3,Lot Area,2930,10147.922,9436.500,7880.018,0.7765,1300.000,215245.000,213945.000,7440.250,11555.250,4115.000,12.8209,265.0237
4,Overall Qual,2930,6.095,6.000,1.411,0.2315,1.000,10.000,9.000,5.000,7.000,2.000,0.1906,0.0524
5,Overall Cond,2930,5.563,5.000,1.112,0.1998,1.000,9.000,8.000,5.000,6.000,1.000,0.5744,1.4914
6,Year Built,2930,1971.356,1973.000,30.245,0.0153,1872.000,2010.000,138.000,1954.000,2001.000,47.000,-0.6045,-0.5017
7,Year Remod/Add,2930,1984.267,1993.000,20.860,0.0105,1950.000,2010.000,60.000,1965.000,2004.000,39.000,-0.4519,-1.3415
8,Mas Vnr Area,2907,101.897,0.000,179.113,1.7578,0.000,1600.000,1600.000,0.000,164.000,164.000,2.6070,9.2866
9,BsmtFin SF 1,2929,442.630,370.000,455.591,1.0293,0.000,5644.000,5644.000,0.000,734.000,734.000,1.4162,6.8593
10,BsmtFin SF 2,2929,49.722,0.000,169.168,3.4023,0.000,1526.000,1526.000,0.000,0.000,0.000,4.1400,18.7815
11,Bsmt Unf SF,2929,559.263,466.000,439.494,0.7858,0.000,2336.000,2336.000,219.000,802.000,583.000,0.9231,0.4095
12,Total Bsmt SF,2929,1051.615,990.000,440.615,0.4190,0.000,6110.000,6110.000,793.000,1302.000,509.000,1.1562,9.1356
13,1st Flr SF,2930,1159.558,1084.000,391.891,0.3380,334.000,5095.000,4761.000,876.250,1384.000,507.750,1.4694,6.9688
14,2nd Flr SF,2930,335.456,0.000,428.396,1.2771,0.000,2065.000,2065.000,0.000,703.750,703.750,0.8665,-0.4149
15,Low Qual Fin SF,2930,4.677,0.000,46.311,9.9022,0.000,1064.000,1064.000,0.000,0.000,0.000,12.1182,175.6069
16,Gr Liv Area,2930,1499.690,1442.000,505.509,0.3371,334.000,5642.000,5308.000,1126.000,1742.750,616.750,1.2741,4.1378
17,Bsmt Full Bath,2928,0.431,0.000,0.525,1.2167,0.000,3.000,3.000,0.000,1.000,1.000,0.6166,-0.7480
18,Bsmt Half Bath,2928,0.061,0.000,0.245,4.0117,0.000,2.000,2.000,0.000,0.000,0.000,3.9408,14.9217
19,Full Bath,2930,1.567,2.000,0.553,0.3530,0.000,4.000,4.000,1.000,2.000,1.000,0.1720,-0.5414
20,Half Bath,2930,0.380,0.000,0.503,1.3244,0.000,2.000,2.000,0.000,1.000,1.000,0.6977,-1.0303
21,Bedroom AbvGr,2930,2.854,3.000,0.828,0.2900,0.000,8.000,8.000,2.000,3.000,1.000,0.3057,1.8914
22,Kitchen AbvGr,2930,1.044,1.000,0.214,0.2050,0.000,3.000,3.000,1.000,1.000,0.000,4.3138,19.8697
23,TotRms AbvGrd,2930,6.443,6.000,1.573,0.2441,2.000,15.000,13.000,5.000,7.000,2.000,0.7535,1.1546
24,Fireplaces,2930,0.599,1.000,0.648,1.0811,0.000,4.000,4.000,0.000,1.000,1.000,0.7392,0.1015
25,Garage Yr Blt,2771,1978.132,1979.000,25.528,0.0129,1895.000,2207.000,312.000,1960.000,2002.000,42.000,-0.3847,1.8266
26,Garage Cars,2929,1.767,2.000,0.761,0.4305,0.000,5.000,5.000,1.000,2.000,1.000,-0.2198,0.2450
27,Garage Area,2929,472.820,480.000,215.047,0.4548,0.000,1488.000,1488.000,320.000,576.000,256.000,0.2420,0.9510
28,Wood Deck SF,2930,93.752,0.000,126.362,1.3478,0.000,1424.000,1424.000,0.000,168.000,168.000,1.8427,6.7540
29,Open Porch SF,2930,47.533,27.000,67.483,1.4197,0.000,742.000,742.000,0.000,70.000,70.000,2.5354,10.9543
30,Enclosed Porch,2930,23.012,0.000,64.139,2.7872,0.000,1012.000,1012.000,0.000,0.000,0.000,4.0144,28.4872
31,3Ssn Porch,2930,2.592,0.000,25.141,9.6977,0.000,508.000,508.000,0.000,0.000,0.000,11.4038,149.9887
32,Screen Porch,2930,16.002,0.000,56.087,3.5050,0.000,576.000,576.000,0.000,0.000,0.000,3.9575,17.8592
33,Pool Area,2930,2.243,0.000,35.597,15.8679,0.000,800.000,800.000,0.000,0.000,0.000,16.9391,299.7749
34,Misc Val,2930,50.635,0.000,566.344,11.1848,0.000,17000.000,17000.000,0.000,0.000,0.000,21.9998,566.2033
35,Mo Sold,2930,6.216,6.000,2.714,0.4367,1.000,12.000,11.000,4.000,8.000,4.000,0.1926,-0.4546
36,Yr Sold,2930,2007.790,2008.000,1.317,0.0007,2006.000,2010.000,4.000,2007.000,2009.000,2.000,0.1349,-1.1576
37,SalePrice,2930,180796.060,160000.000,79886.692,0.4419,12789.000,755000.000,742211.000,129500.000,213500.000,84000.000,1.7435,5.1189

### Quality Table for Numerical Features Descriptive Stats

In [11]:
def get_numerical_quality_table(report):
    
    """
    This function receives a report DataFrame and returns a table with the quality of every numerical feature based on the following criteria:
    - Coefficient of Variation (CV) >= 0.7 indicates high variability relative to the mean
    - | Skewness | > 1  indicates a highly skewed distribution 
    - | Skewness | >= 0.5 indicates a moderately skewed distribution
    - Kurtosis >= 3 indicates heavy tails
    - Kurtosis high extreme values (e.g., > 10) indicate the presence of strong outliers
    """

    quality_table = []

    for _ , row in report.iterrows():

        quality_list = []

        feature = row['Feature']
        cv = pd.to_numeric(row['Coefficient of Variation'], errors='coerce')
        skewness = pd.to_numeric(row['Skewness'], errors='coerce')
        kurtosis = pd.to_numeric(row['Kurtosis'], errors='coerce')

        if cv >= 0.7:
            quality_list.append('High Variability')
        
        if abs(skewness) > 1:
            quality_list.append('Highly Skewed')
        elif abs(skewness) >= 0.5:
            quality_list.append('Moderately Skewed')


        if kurtosis >= 3 and kurtosis <= 10:
            quality_list.append('Heavy Tails')
        elif kurtosis > 10:
            quality_list.append('Extreme Outliers')

        quality_table.append({
            "Feature": feature,
            "Challenges": ', '.join(quality_list) if quality_list else 'Statistically well-behaved'
        })

    return pd.DataFrame(quality_table)

In [12]:
quality_report = get_numerical_quality_table(report)
quality_report

            Feature                                         Challenges
0             Order                         Statistically well-behaved
1               PID                         Statistically well-behaved
2      Lot Frontage                    Highly Skewed, Extreme Outliers
3          Lot Area  High Variability, Highly Skewed, Extreme Outliers
4      Overall Qual                         Statistically well-behaved
5      Overall Cond                                  Moderately Skewed
6        Year Built                                  Moderately Skewed
7    Year Remod/Add                         Statistically well-behaved
8      Mas Vnr Area       High Variability, Highly Skewed, Heavy Tails
9      BsmtFin SF 1       High Variability, Highly Skewed, Heavy Tails
10     BsmtFin SF 2  High Variability, Highly Skewed, Extreme Outliers
11      Bsmt Unf SF                High Variability, Moderately Skewed
12    Total Bsmt SF                         Highly Skewed, Heavy Tails
13       1st Flr SF                         Highly Skewed, Heavy Tails
14       2nd Flr SF                High Variability, Moderately Skewed
15  Low Qual Fin SF  High Variability, Highly Skewed, Extreme Outliers
16      Gr Liv Area                         Highly Skewed, Heavy Tails
17   Bsmt Full Bath                High Variability, Moderately Skewed
18   Bsmt Half Bath  High Variability, Highly Skewed, Extreme Outliers
19        Full Bath                         Statistically well-behaved
20        Half Bath                High Variability, Moderately Skewed
21    Bedroom AbvGr                         Statistically well-behaved
22    Kitchen AbvGr                    Highly Skewed, Extreme Outliers
23    TotRms AbvGrd                                  Moderately Skewed
24       Fireplaces                High Variability, Moderately Skewed
25    Garage Yr Blt                         Statistically well-behaved
26      Garage Cars                         Statistically well-behaved
27      Garage Area                         Statistically well-behaved
28     Wood Deck SF       High Variability, Highly Skewed, Heavy Tails
29    Open Porch SF  High Variability, Highly Skewed, Extreme Outliers
30   Enclosed Porch  High Variability, Highly Skewed, Extreme Outliers
31       3Ssn Porch  High Variability, Highly Skewed, Extreme Outliers
32     Screen Porch  High Variability, Highly Skewed, Extreme Outliers
33        Pool Area  High Variability, Highly Skewed, Extreme Outliers
34         Misc Val  High Variability, Highly Skewed, Extreme Outliers
35          Mo Sold                         Statistically well-behaved
36          Yr Sold                         Statistically well-behaved
37        SalePrice                         Highly Skewed, Heavy Tails

## Univariate Analysis of Categorical Variables

In [ ]:
def create_report_categorical_features(df, categorical_features, rare_threshold=0.05):
    """
    This function receives a DataFrame and a list of categorical features and returns a report with 
    the following information for each categorical feature:
    - Absolute frequency of each category
    - Cardinality (number of unique categories)
    - Cardinality Level (Low, Medium, High)
    - Biggest Category Percentage
    - Number of Rare Levels (categories with low frequency, e.g., less than 5% of the total, or with less than 10 occurrences)
    - Percentage of Rare Levels
    - Missing Percentage
    """

    report = []

    for col in categorical_features:
       
        counts = df[col].value_counts()
        rel_freqs = df[col].value_counts(normalize=True)
        
        total_observations = counts.sum()
        cardinality = len(counts)
        biggest_category_pct = rel_freqs.max() * 100

        rare_mask = (rel_freqs < rare_threshold) | (counts < 10)
        rare_count = rare_mask.sum()
        rare_pct = rel_freqs[rare_mask].sum() * 100

        missing_pct = df[col].isnull().mean() * 100

        def cardinality_level(cardinality):
            if cardinality < 10:
                return 'Low Cardinality'
            elif cardinality <= 30:
                return 'Medium Cardinality'
            else:
                return 'High Cardinality'

        report.append({
            "Feature": col,
            "Total Non-Nulls": total_observations,
            "Cardinality": cardinality,
            "Cardinality Level": cardinality_level(cardinality),
            "Biggest Category %": f"{biggest_category_pct:.2f}%",
            "Rare Levels Count": rare_count,
            "Rare Levels Total %": f"{rare_pct:.2f}%",
            "Missing %": f"{missing_pct:.2f}%"
        })

    return pd.DataFrame(report)

In [60]:
categorical_report = create_report_categorical_features(df, categorical_features)
categorical_report

,Feature,Total Non-Nulls,Cardinality,Cardinality Level,Biggest Category %,Rare Levels Count,Rare Levels Total %,Missing %
0,MS SubClass,2930,16,Medium Cardinality,36.83%,12,27.20%,0.00%
1,MS Zoning,2930,7,Low Cardinality,77.58%,5,6.66%,0.00%
2,Street,2930,2,Low Cardinality,99.59%,1,0.41%,0.00%
3,Alley,198,2,Low Cardinality,60.61%,0,0.00%,93.24%
4,Lot Shape,2930,4,Low Cardinality,63.45%,2,3.14%,0.00%
5,Land Contour,2930,4,Low Cardinality,89.86%,3,10.14%,0.00%
6,Utilities,2930,3,Low Cardinality,99.90%,2,0.10%,0.00%
7,Lot Config,2930,5,Low Cardinality,73.04%,2,3.38%,0.00%
8,Land Slope,2930,3,Low Cardinality,95.19%,2,4.81%,0.00%
9,Neighborhood,2930,28,Medium Cardinality,15.12%,20,38.33%,0.00%
10,Condition 1,2930,9,Low Cardinality,86.08%,7,8.33%,0.00%
11,Condition 2,2930,8,Low Cardinality,98.98%,7,1.02%,0.00%
12,Bldg Type,2930,5,Low Cardinality,82.76%,3,9.28%,0.00%
13,House Style,2930,8,Low Cardinality,50.55%,5,8.94%,0.00%
14,Roof Style,2930,6,Low Cardinality,79.22%,4,1.98%,0.00%
15,Roof Matl,2930,8,Low Cardinality,98.53%,7,1.47%,0.00%
16,Exterior 1st,2930,16,Medium Cardinality,35.02%,11,12.66%,0.00%
17,Exterior 2nd,2930,17,Medium Cardinality,34.64%,12,13.34%,0.00%
18,Mas Vnr Type,1155,4,Low Cardinality,76.19%,2,2.25%,60.58%
19,Exter Qual,2930,4,Low Cardinality,61.40%,2,4.85%,0.00%
20,Exter Cond,2930,5,Low Cardinality,87.00%,3,2.80%,0.00%
21,Foundation,2930,6,Low Cardinality,44.71%,3,2.22%,0.00%
22,Bsmt Qual,2850,5,Low Cardinality,45.02%,2,3.16%,2.73%
23,Bsmt Cond,2850,5,Low Cardinality,91.79%,4,8.21%,2.73%
24,Bsmt Exposure,2847,4,Low Cardinality,66.95%,0,0.00%,2.83%
25,BsmtFin Type 1,2850,6,Low Cardinality,30.14%,0,0.00%,2.73%
26,BsmtFin Type 2,2849,6,Low Cardinality,87.71%,5,12.29%,2.76%
27,Heating,2930,6,Low Cardinality,98.46%,5,1.54%,0.00%
28,Heating QC,2930,5,Low Cardinality,51.02%,2,3.24%,0.00%
29,Central Air,2930,2,Low Cardinality,93.31%,0,0.00%,0.00%
30,Electrical,2929,5,Low Cardinality,91.57%,3,2.01%,0.03%
31,Kitchen Qual,2930,5,Low Cardinality,50.99%,2,2.42%,0.00%
32,Functional,2930,8,Low Cardinality,93.11%,7,6.89%,0.00%
33,Fireplace Qu,1508,5,Low Cardinality,49.34%,3,10.88%,48.53%
34,Garage Type,2773,6,Low Cardinality,62.42%,3,2.67%,5.36%
35,Garage Finish,2771,3,Low Cardinality,44.42%,0,0.00%,5.43%
36,Garage Qual,2771,5,Low Cardinality,94.37%,4,5.63%,5.43%
37,Garage Cond,2771,5,Low Cardinality,96.17%,4,3.83%,5.43%
38,Paved Drive,2930,3,Low Cardinality,90.51%,1,2.12%,0.00%
39,Pool QC,13,4,Low Cardinality,30.77%,4,100.00%,99.56%
40,Fence,572,4,Low Cardinality,57.69%,1,2.10%,80.48%
41,Misc Feature,106,5,Low Cardinality,89.62%,4,10.38%,96.38%
42,Sale Type,2930,10,Medium Cardinality,86.55%,8,5.29%,0.00%
43,Sale Condition,2930,6,Low Cardinality,82.35%,3,2.80%,0.00%